version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:9.0
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: recipes_db
      MYSQL_USER: user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - mysql_root_password
      - mysql_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    depends_on:
      - db

volumes:
  db_data:

secrets:
  mysql_root_password:
    file: ./secrets/secrets_mysql_root_password.txt
  mysql_password:
    file: ./secrets/secrets_mysql_password.txt
